<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class MyEquipmentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('my_equipments')->insert([
            [
                'user_id' => 1,
                'user_height' => '普通',
                'user_age' => '30代前半',
                'experience_period' => 10,
                'racket_id' => 9,
                'stringing_way' => 'single',
                'main_gut_id' => 1,
                'cross_gut_id' => 1,
                'main_gut_guage' => 1.25,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 50,
                'cross_gut_tension' => 50,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 2,
                'user_height' => 'やや小柄',
                'user_age' => '20代前半',
                'experience_period' => 3,
                'racket_id' => 7,
                'stringing_way' => 'hybrid',
                'main_gut_id' => 1,
                'cross_gut_id' => 2,
                'main_gut_guage' => 1.25,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 50,
                'cross_gut_tension' => 48,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 3,
                'user_height' => 'やや小柄',
                'user_age' => '40代前半',
                'experience_period' => 3,
                'racket_id' => 8,
                'stringing_way' => 'single',
                'main_gut_id' => 2,
                'cross_gut_id' => 2,
                'main_gut_guage' => 1.30,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 52,
                'cross_gut_tension' => 50,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'user_height' => '普通',
                'user_age' => '30代前半',
                'experience_period' => 10,
                'racket_id' => 9,
                'stringing_way' => 'single',
                'main_gut_id' => 9,
                'cross_gut_id' => 9,
                'main_gut_guage' => 1.25,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 50,
                'cross_gut_tension' => 50,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 2,
                'user_height' => 'やや小柄',
                'user_age' => '20代前半',
                'experience_period' => 3,
                'racket_id' => 7,
                'stringing_way' => 'hybrid',
                'main_gut_id' => 5,
                'cross_gut_id' => 6,
                'main_gut_guage' => 1.25,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 50,
                'cross_gut_tension' => 48,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 3,
                'user_height' => 'やや小柄',
                'user_age' => '40代前半',
                'experience_period' => 3,
                'racket_id' => 8,
                'stringing_way' => 'single',
                'main_gut_id' => 4,
                'cross_gut_id' => 4,
                'main_gut_guage' => 1.30,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 52,
                'cross_gut_tension' => 50,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 1,
                'user_height' => '普通',
                'user_age' => '30代前半',
                'experience_period' => 10,
                'racket_id' => 9,
                'stringing_way' => 'single',
                'main_gut_id' => 5,
                'cross_gut_id' => 5,
                'main_gut_guage' => 1.25,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 50,
                'cross_gut_tension' => 50,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 2,
                'user_height' => 'やや小柄',
                'user_age' => '20代前半',
                'experience_period' => 3,
                'racket_id' => 7,
                'stringing_way' => 'hybrid',
                'main_gut_id' => 3,
                'cross_gut_id' => 7,
                'main_gut_guage' => 1.25,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 50,
                'cross_gut_tension' => 48,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'user_id' => 3,
                'user_height' => 'やや小柄',
                'user_age' => '40代前半',
                'experience_period' => 3,
                'racket_id' => 8,
                'stringing_way' => 'single',
                'main_gut_id' => 8,
                'cross_gut_id' => 8,
                'main_gut_guage' => 1.30,
                'cross_gut_guage' => 1.25,
                'main_gut_tension' => 52,
                'cross_gut_tension' => 50,
                'new_gut_date' => Carbon::now(),
                'change_gut_date' => null,
                'comment' => '',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ]);
    }
}
